- README.md
ivy.load -> classpath.add 
the pageHTML() method no longer seems to be on the spec property and is now on the chart. 
Tested in jupyter-scala.
> Updating  README.md

- build.sbt
- project/plugins.sbt
- version.sbt
Adding SBT plugins that make releases easier. 
Running ```sbt release``` does:
* Runs tests
* Tags the release (which means it goes into the releases section on github)
* Automates the tedious Maven central / Sonatype release process 
* Increments ```version.sbt``` 
New process is also documented in CONTRIB.md.
Also added Roger as author in POM.xml file :)
> sbt-release + sbt-sonatype support

- .travis.yml
- build.sbt
- core/src/test/scala/vegas/DSL/AllDSLs.scala
- project/build.properties
Addresses #36.
Changes the .travis.yml file so that Travis CI now uses installs chromedriver correctly, so that tests can run.
Also downgraded sbt to 0.13.10 since that's the latest available on Ubuntu.
> Travis build fixed

- core/src/main/scala/vegas/DSL/ConfigDSL.scala
- core/src/main/scala/vegas/DSL/DataDSL.scala
- core/src/main/scala/vegas/DSL/EncoderDSL.scala
- core/src/main/scala/vegas/DSL/package.scala
- core/src/main/scala/vegas/data/FieldExtractor.scala
- core/src/main/scala/vegas/data/SimpleTypeUtils.scala
- core/src/main/scala/vegas/data/ValueTransformer.scala
- core/src/main/scala/vegas/package.scala
- core/src/main/scala/vegas/render/StaticHTMLRenderer.scala
- core/src/main/scala/vegas/render/WindowRenderer.scala
- core/src/test/scala/vegas/DSL/DataDSLSpec.scala
- core/src/test/scala/vegas/data/FieldExtractorSpec.scala
- core/src/test/scala/vegas/data/SimpleTypeUtilsSpec.scala
- core/src/test/scala/vegas/fixtures/BasicPlots.scala
- core/src/test/scala/vegas/fixtures/VegasPlots.scala
- core/src/test/scala/vegas/render/StaticHTMLRendererSpec.scala
- core/src/test/scala/vegas/render/WindowRendererSpec.scala
- flink/src/main/scala/vegas/flink/Flink.scala
- spark/src/main/scala/vegas/spark/Spark.scala
Attempt to clean up the top level API. 
Changes:
* withData methods renamed and given documentation. New ones hopefully are easier to understand. Feedback welcome on better names though...
* Top-level namespace was getting quite polluted. Pruned it a bit, and put some operations under objects (i.e. AggOps.Sum) 
* Added support for encoding values that are Dates (basically just formatted to the ISO-8601)
* Added support for overriding how Any values are converted to JS friendly values, via an implicit argument. 
* Refactored various "type detecting code" into a `vegas.data.*` package. Added unit tests for this code.
* Added unit tests for WindowRenderer, and tidied up some of that code (I didn't really understand what I was doing with JavaFX. Still don't really, but understand a little …
> Refactoring data API

- build.sbt
- core/src/main/scala/vegas/data/ValueTransformer.scala
- core/src/test/scala/vegas/DSL/DataDSLSpec.scala
- core/src/test/scala/vegas/data/ValueTransformerSpec.scala
- core/src/test/scala/vegas/util/Time.scala
- spark/src/main/scala/vegas/sparkExt/package.scala
- spark/src/test/scala/vegas/sparkExt/SparkExtSpec.scala
Part of fix for #76.
* ValueTransformer now supports null types, Sql Dates and Timestamps, and Options
* Added seconds to Date formatting (was missing before)
* Added Spark unit test with more complex data types 
* Changed default limit in Spark to 10,000
> ValueTransformer now supports null types, Dates, and Options

- core/src/main/scala/vegas/render/BaseHTMLRenderer.scala
Using HTTP breaks HTML for content served over HTTPS. The CDN supports HTTP/2, so it's faster to fetch from HTTPS anyway.
Another option is omitting the scheme and letting the browser resolve it, however this would break HTML served from `file://` with no real benefit.
> Use HTTPS for CDN

- README.md
The API of jupyter-scala seems to have changed slightly:
Adding the dependency now works via the `$ivy` pattern and `display` seems to be `publish` now.
> Fix jupyter-scala usage

- core/src/main/scala/vegas/package.scala
In plotting histograms as bar charts, you don't want the domain values sorted, but rendered in the order they were provided. Vega-Lite provides for this, but wasn't exposed fully in the Vegas DSL.
> Expose `Spec.SortOrderEnums.None` in DSL

- core/src/main/scala/vegas/DSL/SpecDSL.scala
- core/src/main/scala/vegas/render/BaseHTMLRenderer.scala
- core/src/main/scala/vegas/render/ShowRender.scala
- core/src/main/scala/vegas/render/StaticHTMLRenderer.scala
- core/src/main/scala/vegas/render/WindowRenderer.scala
- core/src/test/scala/vegas/render/ShowSpec.scala
- core/src/test/scala/vegas/render/StaticHTMLRendererSpec.scala
- core/src/test/scala/vegas/render/WindowRendererSpec.scala
- core/src/test/scala/vegas/util/WebGenerators.scala
- macros/src/main/scala/vegas/macros/ShowRenderMacros.scala
- spec/src/main/scala/vegas/spec/Spec.scala
* Replace implicit conversions with implicit ops class
* Introduce implicit class `ShowRender`
* Macro guesses appropriate default `ShowRender` instance
* Eliminates the need for import boilerplate in notebooks
I did this mainly because implicit views can often cause problems due to variance of the type arguments; making an invariant subtrait resolves that problem. Since we're already using macros, we can also go ahead and guess which of several common environments we're in (based on README) and build a default instance to the environment.
> DSL Improvements

- README.md
- core/src/test/scala/vegas/render/ShowSpec.scala
- macros/src/main/scala/vegas/macros/ShowRenderMacros.scala
- Fixes macro for Zeppelin (wrong type signature of DisplayUtils.html)
- Update docs to describe how ShowRender is used in manual cases
> Fix macro for Zeppelin

- core/src/test/scala/vegas/util/NotebookGenerator.scala
- notebooks/jupyter_example.ipynb
- notebooks/zeppelin_example.json
Fixing Jupyter and Zeppelin NotebookGenerator with the two changes:
1.  Change artifact groupId from ``com.github.aishfenton`` to ``org.vegas-viz``
2.  Update the ``implicit val render`` to the newly added ``vegas.render.ShowHTML``
Note that @izhangzhihao had earlier fixed the jupyter notebook without adjusting the NotebookGenerator. Hence, you will see more diffs in the jupyter_example.ipynb.
> Fix notebooks (imports and ShowHTML)

- core/src/test/scala/vegas/util/NotebookGenerator.scala
- notebooks/jupyter_example.ipynb
- notebooks/zeppelin_example.json
After Jeremy's fixes below, the implicit renderer variable is no longer required:
https://github.com/vegas-viz/Vegas/pull/86
https://github.com/vegas-viz/Vegas/pull/99
Hence, taking it off in the NotebookGenerator.
> Remove implicit val renderer from generated notebooks

- core/src/main/scala/vegas/render/StaticHTMLRenderer.scala
- core/src/test/scala/vegas/render/StaticHTMLRendererSpec.scala
This doesn't solve the issue with iframe resizing, though it's certainly something that should be done to ensure the element targeted for vega exists.
> Create the targeted element before the script

- core/src/main/scala/vegas/render/StaticHTMLRenderer.scala
This fixes some issues folks were having when there were multiple vegas plots on one page while also making a non-jquery way of plotting.
* The function declaration is done in an [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression) so nothing else overwrites the function declaration
* `document.querySelector` is used instead of `$()`
* since the output here is done _well_ after the document is ready, I've removed the jquery `onReady`
If people like this change, I'll update for the tests too.
> Remove all use of jQuery, wrap invocation in IIFE

- build.sbt
- core/src/test/scala/vegas/WebMatchers.scala
- core/src/test/scala/vegas/integration/PlotHtml.scala
- project/build.properties
- project/plugins.sbt
- bumps sbt version to 1.1.0. 
- adds explicit dep on scala-xml, which was preventing a build on 2.12 (and also a [weird bug](https://issues.scala-lang.org/browse/SI-8358) in the scala compiler ). 
- bumps various library versions. enables cross-compile of base vegas module on 2.12.
> Enable publishing core + macros for 2.12

- core/src/main/scala/vegas/render/StaticHTMLRenderer.scala
When I tried the [example notebook](http://nbviewer.jupyter.org/github/aishfenton/Vegas/blob/master/notebooks/jupyter_example.ipynb) with [jupyter-scala](https://github.com/jupyter-scala/jupyter-scala) (on Chromium browser v64.0.3282.140), I 
have noticed that the user agent stylesheet increases the height of the content in iframe and then a scroll bar appears.
In order to disable body margin of user agent stylesheet, I added `margin: 0px;` to `<body>` tag.
> Disable body margin of user agent stylesheet

- core/src/test/scala/vegas/DSL/AllDSLSpec.scala
- core/src/test/scala/vegas/fixtures/BasicPlots.scala
- core/src/test/scala/vegas/fixtures/VegasPlots.scala
- core/src/test/scala/vegas/integration/PlotHtml.scala
It devides test cases (`Basic plots should render HTML without error` and `Vegas plots should render HTML without error`) into plots.
```
[info] PlotHtml:
[info] Basic plots
[info] - should render HTML without error (3 seconds, 28 milliseconds)
[info] Vegas plots
[info] - should render HTML without error (470 milliseconds)
[info] Run completed in 5 seconds, 113 milliseconds.
```
```
[info] PlotHtml:
[info] Basic plots
[info] - should render HTML without error area (366 milliseconds)
[info] - should render HTML without error bar (160 milliseconds)
[info] - should render HTML without error bar_aggregate (37 milliseconds)
[info] - should render HTML without error bar_grouped (40 milliseconds)
[info] - should render HTML without error github_punchcard (39 milliseconds)
[info] - should render …
```
> Refactor fixtures.{Basic,Vegas}Plots.scala

- core/src/main/scala/vegas/spec/Spec.scala
Reverts vegas-viz/Vegas#137
I have noticed that Spec.scala was generated automatically.
I will add an warning message (ex. `Do NOT edit this file manually`) in another PR.
https://github.com/vegas-viz/Vegas/blob/1496432875f80e9e579cc584fa8fd299f34a71a6/build.sbt#L46
https://github.com/vegas-viz/Vegas/blob/1496432875f80e9e579cc584fa8fd299f34a71a6/CONTRIB.md#dev-and-debugging-tips
> Revert "Refactor spec/Spec.scala"

- build.sbt
```
/home/travis/build/vegas-viz/Vegas/build.sbt:145: warning: Adaptation of argument list by inserting () is deprecated: this is unlikely to be what you want.
signature: DefinableTask.:=(v: S): sbt.Def.Setting[sbt.Task[S]]
given arguments: <none>
after adaptation: DefinableTask.:=((): Unit)
publish := ()
^
/home/travis/build/vegas-viz/Vegas/build.sbt:146: warning: Adaptation of argument list by inserting () is deprecated: this is unlikely to be what you want.
signature: DefinableTask.:=(v: S): sbt.Def.Setting[sbt.Task[S]]
given arguments: <none>
after adaptation: DefinableTask.:=((): Unit)
publishLocal := ()
```
https://travis-ci.org/vegas-viz/Vegas/jobs/402833152#L790-L801
> Fix deprecated warnings on build.sbt

- build.sbt
It will resolve a circular dependency.
```
[warn] circular dependency found: org.seleniumhq.selenium#selenium-java;3.0.0-beta2->com.github.detro.ghostdriver#phantomjsdriver;1.1.0->org.seleniumhq.selenium#selenium-java;2.39.0
[warn] circular dependency found: org.seleniumhq.selenium#selenium-java;3.0.0-beta2->com.github.detro.ghostdriver#phantomjsdriver;1.1.0->org.seleniumhq.selenium#selenium-server;2.39.0->org.seleniumhq.selenium#selenium-java;2.39.0
[info] Done updating.
[info] Updating spark...
[info] Compiling 2 Scala sources to /home/travis/build/vegas-viz/Vegas/macros/target/scala-2.11/classes ...
[warn] circular dependency found: org.seleniumhq.selenium#selenium-java;3.0.0-beta2->com.github.detro.ghostdriver#phantomjsdriver;1.1.0->org.seleniumhq.selenium#selenium-java;2.39.0
[warn] …
```
> Update selenium-java to v3.13.0

- core/src/test/resources/log4j.properties
Suppress Spark's INFO logs because they are verbose.
before: https://travis-ci.org/vegas-viz/Vegas/jobs/439251181#L1058-L1441
after: https://travis-ci.org/vegas-viz/Vegas/jobs/445184508#L1047-L1048
> Suppress Spark's `INFO` logs at test time

- codecov.yml
Ignore Spec.scala because it is automatically generated from jsonschema.
<https://docs.codecov.io/docs/ignoring-paths>
> Ignore Spec.scala when calculating coverage
